POST http://localhost:3000/quatro_product/create
Content-Type: application/json

{
    "product_name":"Mineral Water",
    "product_description" : "Sky juice",
    "product_category": "Drinks",
    "product_price": 2.50,
    "product_quantity": "100",
    "product_image": "https://cdn1-production-images-kly.akamaized.net/QzTTZqGXM5PqL9REm9okFMn-r20=/1200x1200/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/2702436/original/016317800_1547270165-shutterstock_314020379.jpg"
}

###

POST http://localhost:3000/quatro_product/create
Content-Type: application/json

{
    "product_name":"Tropicana Apple Juice 320ml",
    "product_description":"Apple Juice to your daily routine for a delicious and convenient source of vitamin C. Refreshing apple juice with a deliciously sweet taste",
    "product_category":"Juice",
    "product_price": 3.45,
    "product_quantity":"100",
    "product_image":"https://m.media-amazon.com/images/I/61cPgyyfqEL._SL1500_.jpg "
}

###

POST http://localhost:3000/quatro_product/create
Content-Type: application/json

{
    "product_name":"My Mochi Ice Cream Cookies & Cream 6S 180G ",
    "product_description":"Edible method: Defrosted ready to eat(Do not repeatedly defrost to affect the quality, 1% recommended half defrost flavour best) KEEP FROZEN AT -18°C OR BELOW",
    "product_category":"Bread & Pastry",
    "product_price": 10.99,
    "product_quantity":"100",
    "product_image":"https://www.mymochi.com/wp-content/uploads/2018/12/Smores-110cals_no-shadow_400.png "
}