###
POST http://localhost:5004/quatro_user/minus_credit
Content-Type: application/json

{
   "user_credit" : "30",
   "user_id" : "1"
}

###
POST http://localhost:5004/quatro_user/add_credit
Content-Type: application/json

{
   "user_credit" : "10",
   "user_id" : "1"
}
