GET http://localhost:5000/quatro_address/get


###
POST http://localhost:5000/quatro_address/create
Content-Type: application/json

{
    "address_line_1": "No 12",
    "address_line_2": "",
    "address_line_3": "Taman Pakatan Jaya",
    "postcode": "31150 Ulu Kinta",
    "state": "Perak",
    "user_id": "1"
}

###
POST http://localhost:5004/quatro_address/update_details
Content-Type: application/json

{
    "address_line_1": "No 2",
    "address_line_2": "Persiaran Jaya 7",
    "address_line_3": "21 Street",
    "postcode": "12345 Gae",
    "state": "Pop",
    "address_id": "7"
}

###
DELETE http://localhost:5000/quatro_address/delete
Content-Type: application/json

{
    "address_id" : "9"
}