


###
POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Mineral Water",
    "product_description" : "Sky juice",
    "product_category": "Drinks",
    "product_price": 2.50,
    "product_quantity": "100",
    "product_image": "https://cdn1-production-images-kly.akamaized.net/QzTTZqGXM5PqL9REm9okFMn-r20=/1200x1200/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/2702436/original/016317800_1547270165-shutterstock_314020379.jpg"
}



###
POST http://localhost:5004/quatro_product/update_details
Content-Type: application/json

{

    "product_name":"",
    "product_description" :"",
    "product_category": "Tea",
    "product_image": "https://www.miizu.my/image/digitalgrocer/image/cache/data/all_product_images/product-204/3%20new-1080x1080.png",
    "product_id" : "5"


}

###
POST http://localhost:5004/quatro_product/update_price
Content-Type: application/json

{
    "product_price": "3.79",
    "product_id": "59"
}

update quatro_product set product_quantity = product_quantity - $1 where product_id = $2

###
POST http://localhost:5004/quatro_product/update_quantity
Content-Type: application/json

{
    "product_quantity": "6",
    "product_id": "2"
}

###
POST http://localhost:5004/quatro_product/minus_quantity
Content-Type: application/json

{
    "product_quantity": "5",
    "product_id": "16"
}


###
DELETE http://localhost:5004/quatro_product/delete
Content-Type: application/json

{
    "product_id" : "59"
}