

GET http://localhost:5004/quatro_address/get
Content-Type: application/json

{
    "user_id": "77"
}


###
POST http://localhost:5004/quatro_address/create
Content-Type: application/json

{
    "address_line_1": "No 1",
    "address_line_2": "Taman Mewah",
    "address_line_3": "Dengkil",
    "postcode": "12345",
    "state": "Selangor",
    "user_id": "77"
}

###
POST http://localhost:5004/quatro_address/update_details
Content-Type: application/json

{
    "address_line_1": "No 18",
    "address_line_2": "Taman Bukit Mewah",
    "address_line_3": "Seremban",
    "postcode": "abccc",
    "state": "Negeri Sembilan",
    "address_id": "117"
}

###
DELETE http://localhost:5004/quatro_address/delete
Content-Type: application/json

{
    "address_id" : "5"
}