###
POST http://localhost:5004/quatro_transaction/create
Content-Type: application/json

{
      "transaction_id": "1",
      "product_id": "3",
      "user_id": "1",
      "product_name": "Kicap Pedas Manis Mahsuri",
      "product_quantity": "2",
      "product_price": "6.2",
      "transaction_timestamp": "2022-11-22 13:36:20" 
}


###
POST http://localhost:5004/quatro_transaction/update
Content-Type: application/json

{

}