# Get User
GET http://localhost:3000/quatro_user

### 
GET http://localhost:3000/quatro_user/John/Doe

### 
POST http://localhost:3000/quatro_user/login
Content-Type: application/json

{
    "email":"newuser@test.com",
    "password":"test1234"
}
### 
POST http://localhost:3000/quatro_user/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJpYXQiOjE2NjgxNTM5OTIsImV4cCI6MTY2ODI0MDM5Mn0.-AivlL2yWRmf8HbmnxP2dRrcN6f4g_XtYdz06tyWshs
Content-Type: application/json

{
    "first_name":"John",
    "last_name":"Wong"
}

###
POST http://localhost:3000/quatro_user/create
Content-Type: application/json

{ 
    "email":"newuser@test.com",
    "password":"test1234"
}

###
POST http://localhost:3000/quatro_user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Njg0MTE2ODksImV4cCI6MTY2ODQ5ODA4OX0.QLgmftQzLcNDWqNvuAidz7ZbgqhrUqD3Rr7ZTuXJamo
Content-Type: application/json

{   
    "first_name": "Ch",
    "last_name": "Nooo",
    "date_of_birth": "2000-08-02",
    "phone_number" : "0192345442",
    "email":"oikj@labuan.com",
    "password":"",
    "user_id" : 6
}
###
DELETE  http://localhost:3002/quatro_user/delete
Content-Type: application/json

{
    "user_id":5
}
