###
POST http://localhost:5004/quatro_cart/create
Content-Type: application/json

{
   "user_id" : "5",
   "product_id" :"10" ,
   "product_quantity" : "2"
}

###
DELETE  http://localhost:5004/quatro_cart/delete
Content-Type: application/json

{
    "user_id": "1"
}

###
POST  http://localhost:5004/quatro_cart/push
Content-Type: application/json

{
    "user_id": "5"
}

###
POST http://localhost:5004/quatro_cart/create_discount
Content-Type: application/json

{
   "user_id" : "5",
   "discount_product_id" : "1",
   "product_quantity" : "4"
}

###
DELETE  http://localhost:5004/quatro_cart/delete_discount
Content-Type: application/json

{  "user_id": "2",
    "discount_product_id": "1"
}

###
POST  http://localhost:5004/quatro_cart/push_discount
Content-Type: application/json

{
    "user_id": "2"
}



