# Get User
GET http://localhost:3001/quatro_user

### 
GET http://localhost:3001/quatro_user/John/Doe

### 
POST http://localhost:3001/quatro_user/login
Content-Type: application/json

{
    "email":"meow@meow.com",
    "password":"meow123"
}
### 
POST http://localhost:3001/quatro_user/search
Content-Type: application/json

{
    "first_name":"Marianne",
    "last_name":"Wong"
}

###
POST http://localhost:3001/quatro_user/create
Content-Type: application/json

{
    "email":"meow@meow.com",
    "password":"meow1234"
}

###
POST http://localhost:3001/quatro_user/update
Content-Type: application/json

{   
    "first_name": "Cheng",
    "last_name": "Ng",
    "date_of_birth": "1999-07-03",
    "phone_number" : "0149728336",
    "email":"vathng99@labuan.com",
    "password":"",
    "user_id" : 2
}
###
DELETE  http://localhost:3001/quatro_user/delete
Content-Type: application/json

{
    "user_id":5
}
