POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Mineral Water",
    "product_description" : "Sky juice",
    "product_category": "Drinks",
    "product_price": 2.50,
    "product_quantity": "100",
    "product_image": "https://cdn1-production-images-kly.akamaized.net/QzTTZqGXM5PqL9REm9okFMn-r20=/1200x1200/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/2702436/original/016317800_1547270165-shutterstock_314020379.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Tropicana Apple Juice 320ml",
    "product_description":"Apple Juice to your daily routine for a delicious and convenient source of vitamin C. Refreshing apple juice with a deliciously sweet taste",
    "product_category":"Juice",
    "product_price": 3.45,
    "product_quantity":"100",
    "product_image":"https://m.media-amazon.com/images/I/61cPgyyfqEL._SL1500_.jpg "
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"My Mochi Ice Cream Cookies & Cream 6S 180G ",
    "product_description":"Edible method: Defrosted ready to eat(Do not repeatedly defrost to affect the quality, 1% recommended half defrost flavour best) KEEP FROZEN AT -18°C OR BELOW",
    "product_category":"Frozen Dairy",
    "product_price": 10.99,
    "product_quantity":"100",
    "product_image":"https://www.mymochi.com/wp-content/uploads/2018/12/Smores-110cals_no-shadow_400.png "
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Strawberry Danish Bread 4 Pcs ",
    "product_description":"This the BEST strawberry danish. It uses frozen puff pastry with fluffy cream cheese filling. On top are fresh strawberries that are baked. To give this pastry a fresh taste, it has a lemon icing drizzle.",
    "product_category":"Bread & Pastry",
    "product_price": 4.99,
    "product_quantity":"100",
    "product_image":"https://www.sugarsaltmagic.com/wp-content/uploads/2022/03/Cream-Cheese-Strawberry-Danish-3FEAT-500x500.jpg "
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Custard Danish Bread 4Pcs ",
    "product_description":"A well-known favourite, the custard Danish pastry, are buttery, flaky pastry circles filled with custard and jam or apricots. ",
    "product_category":"Bread & Pastry",
    "product_price": 4.99,
    "product_quantity":"100",
    "product_image": "https://i.pinimg.com/736x/fc/78/bc/fc78bcc62819f46c153852467e6840e0.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Gardenia Waffles- Chocolate ",
    "product_description":"Contain 1 piece of chocolate flavour waffle 42g ",
    "product_category":"Bread & Pastry",
    "product_price": 1.50,
    "product_quantity":"100",
    "product_image": "https://cdn.shopify.com/s/files/1/0434/5338/2808/products/048244-1-1_8bbb9a20-6c1c-41b6-9e9a-388a128fa196.jpg?v=1665804412"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Gardenia Waffles - Vanilla",
    "product_description":"Contain 1 piece of vanilla waffle 42g",
    "product_category":"Bread & Pastry",
    "product_price": 1.50,
    "product_quantity":"100",
    "product_image": "https://lzd-img-global.slatic.net/g/p/5f501e1a8d75bbe83818e5e8211dacab.jpg_720x720q80.jpg_.webp"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Gardenia Waffles- Orange",
    "product_description":"Contain 1 piece of orange waffle 42g ",
    "product_category":"Bread & Pastry",
    "product_price": 1.50,
    "product_quantity":"100",
    "product_image": "https://cdn.happyfresh.com/t/s_large,c_fit/spree/images/attachments/9df7a15a097e94da9d9bdba7a829117e2fb4263e-original.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Premio Italian Chicken Sausage 120G",
    "product_description":"What’s better than Italian chicken sausage? Premio Italian Chicken Sausage with Cheese & Garlic, of course! This sausage, made with flavorful Romano and Parmesan cheeses and garlic, packs enough flavor to be put on a roll and savored all by itself. It could be a tasty addition to your next pasta dish or the star of meal centered on its mouth-watering flavors. Either way, this delicious sausage is ready to be the star of your next meal today! Find the Premio retailer closest to you, or order online now.",
    "product_category":"Meat",
    "product_price": 5.99,
    "product_quantity":"100",
    "product_image": "https://www.premiofoods.com/content/uploads/2017/04/italian-chicken-sausage.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Sweet Italian Chicken Sausage With Kale",
    "product_description":"We thought adding a superfood like kale to our chicken sausage was a super idea — so we did. Premio Sweet Italian Chicken Sausage with Kale has significantly less fat than USDA data for pork and beef sausage, plus the endless list of benefits from kale. If you’re looking for a sausage that will bring another level of taste without adding extra fat, your search is over. Order now!",
    "product_category":"Meat",
    "product_price": 8.99,
    "product_quantity":"100",
    "product_image": "https://www.premiofoods.com/content/uploads/2017/04/Sweet-Italian-Chicken-Sausage-wKale.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Sweet & Hot Italian Sausage",
    "product_description":"What’s better than getting two in one? Nothing we can think of. That’s why we put two of our most famous Italian sausages in one convenient package — the Premio Hot/Sweet Combo Pack. Now you don’t have to choose between hot and sweet because you can have them both in one.Satisfy the heat lovers and the sweet lovers at your table by using our tasty, convenient hot/sweet combo pack to make an unforgettable meal today.",
    "product_category":"Meat",
    "product_price": 8.99,
    "product_quantity":"100",
    "product_image": "https://www.premiofoods.com/content/uploads/2017/04/Sweet-Italian-Chicken-Sausage.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Dragon Fruit 1pcs",
    "product_description":"Dragon fruit is a food that grows on a climbing cactus called hylocereus, which you'll find in tropical regions around the world. It’s rich in antioxidants like flavonoids, phenolic acid, and betacyanin. These natural substances protect your cells from damage by free radicals -- molecules that can lead to diseases like cancer and premature aging. Sweet and tropical flavour, honey jackfruit generally has a better taste when eaten fresh.",
    "product_category":"Fruit",
    "product_price": 5.50,
    "product_quantity":"100",
    "product_image": "https://dusun.b-cdn.net/wp-content/uploads/2021/09/3-count-image-of-dragon-fruit-white-fruit-28658616893484_600x600.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Nangka Madu/Honey Jack 350g",
    "product_description":"Sweet and tropical flavour, honey jackfruit generally has a better taste when eaten fresh.",
    "product_category":"Fruit",
    "product_price": 6.59,
    "product_quantity":"100",
    "product_image": "https://810freshmart.com/wp-content/uploads/2020/10/Limpek-honey-jackfruit.gif"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Pineapple Sarawak 1pcs",
    "product_description":"Supersweet. Rich of vitamin C. Juicy and tasty.",
    "product_category":"Fruit",
    "product_price": 6.59,
    "product_quantity":"100",
    "product_image": "http://www.kedaiku.nas.my/image/cache/catalog/Kedai%20Runcit/Produk/Fresh%20Food/Fresh%20Fruit/Tropical%20Fruits/Nanas%20Sarawak%20M%201%20Piece-500x500.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Banana Mas-KG",
    "product_description":"Pisang Mas bananas are an excellent source of fiber to regulate the digestive tract, vitamin C to strengthen the immune system, and potassium to balance fluid levels within the body.",
    "product_category":"Fruit",
    "product_price": 5.69,
    "product_quantity":"100",
    "product_image": "https://marketplace.seldec.my/images/thumbnails/1320/1080/detailed/35/berangan.jpeg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Gourmessa Beef Pastrami 100G",
    "product_description":"Gourmessa Beef Pastrami is either made from a cut called the deckle, a lean, wide, firm shoulder cut, or the navel, a smaller and juicier section right below the ribs. The distinctive flavors of pastrami are smoke, spicy black pepper, and the sweet citrus tang of coriander.",
    "product_category":"Meat",
    "product_price": 9.99,
    "product_quantity":"100",
    "product_image": "https://www.checkers.co.za/medias/10536530EA-20190726-Media-checkers515Wx515H.webp?context=bWFzdGVyfGltYWdlc3wyODg4NHxpbWFnZS93ZWJwfGltYWdlcy9oYTEvaDFhLzkwMDQzNDc1NTU4NzAud2VicHxlODU4OWQ3Y2M2M2MwNGVhOGQzMjc4Y2M1Zjc1NTkxYjY0NjcxMjE4NTAzYjFkMTEzNzllYjEyNzc1ODM0YWNh"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Gourmessa Beef Salami 100G",
    "product_description":"Made from premium raw ingredients under supervised and hygienic conditions, Gourmessa Beef Salami guarantees high quality taste in every bite.",
    "product_category":"Meat",
    "product_price": 10.99,
    "product_quantity":"100",
    "product_image": "https://www.desasegar.com.my/storage/media/filemanager/frozen%20food/Gourmessa%20Beef%20Salami%20100g.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Pawada Corned Beef 150G",
    "product_description":"Beef,Starch,Salt,Sugar,Monosodium Glutamate (E621),Sodium Nitrite (E250).",
    "product_category":"Meat",
    "product_price": 9.49,
    "product_quantity":"100",
    "product_image": "https://www.halalfoodmaster.com/images/detailed/3/Untitled_design_zy9w-kj.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Chicken Thigh 1KG",
    "product_description":"Aqina Chicken Thigh, the top portion of the leg above the knee joint that is connected to the body of the chicken. It is a good source of lean protein.",
    "product_category":"Meat",
    "product_price": 10.50,
    "product_quantity":"100",
    "product_image": "https://hearty.com.my/wp-content/uploads/2021/05/C007.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Chicken Wing 1KG",
    "product_description":"Aqina Chicken Wing. Perfect for spicy Asian chicken recipe.",
    "product_category":"Meat",
    "product_price": 17.90,
    "product_quantity":"100",
    "product_image": "https://cdn.store-assets.com/s/377840/i/17108336.jpeg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Chicken Drumstick 1KG",
    "product_description":"Aqina Chicken Drumstick. Perfect for spicy Asian chicken recipe.",
    "product_category":"Meat",
    "product_price": 17.90,
    "product_quantity":"100",
    "product_image": "https://smina.com.mt/wp-content/uploads/2015/11/chicken-drumsticks.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Lively Raspberry Lemon Balm Tea 450ML",
    "product_description":"Calm with the wonder of lemon balm. Known as the 'Elixir of Life', the lemon balm herb has been consumed by many cultures over the ages for the relaxing effects of its refreshing citrusy notes. 100% recyclable.",
    "product_category":"Beverage",
    "product_price": 3.50,
    "product_quantity":"100",
    "product_image": "https://www.nestle.com.my/sites/g/files/pydnoa251/files/lively-tea-calm-thumb.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"FN Seasons Ice Lemon Tea 1L",
    "product_description":"Sedimentation and colour change may occur due to natural ingredients used. Water,Sugar,Citric Acid,Flavourings,Black Tea Extract (contains Tea Polyphenols* 28mg/ 100ml Seasons Ice Lemon Tea),Ascorbic Acid,Lemon Juice,Naturally contains Antioxidant*.",
    "product_category":"Beverage",
    "product_price": 3.50,
    "product_quantity":"100",
    "product_image": "https://d11vuao38tfjvv.cloudfront.net/files/fc4d3bf59470fd659d90901594551d5f3c07be7ba4faace22c7bedadc317b8d6.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"OYOSHI Original Green Tea 1L",
    "product_description":"Sedimentation and colour change may occur due to natural ingredients used. Brewed Jasmine Green Tea,Fructose,Ascorbic Acid,Contains Acidity Regulator (INS452) as Permitted Food Conditioner and Permitted Flavouring Substance,Additives derived from Plant and Synthetic Origin.",
    "product_category":"Beverage",
    "product_price": 3.99,
    "product_quantity":"100",
    "product_image": "https://d11vuao38tfjvv.cloudfront.net/files/fc4d3bf59470fd659d90901594551d5f3c07be7ba4faace22c7bedadc317b8d6.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Lively Pear Schisandra Tea 450ml",
    "product_description":"Used as a traditional Chinese remedy over the centuries, Schisandra berries are believed to promote longevity by helping the body to restore its natural balance of Yin and Yang. 100% recyclable.",
    "product_category":"Beverage",
    "product_price": 3.50,
    "product_quantity":"100",
    "product_image": "https://www.nestle.com.my/sites/g/files/pydnoa251/files/lively-tea-sustain-thumb.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Lively Orange Guarana Tea 450ml",
    "product_description":"For centuries, the Guarani tribes of the Amazon have been brewing Guarana into drinks that they believe help to improve focus and sharpen the senses. We often have those moments when we need clear focus ta tackle our day's priority. Lively Tea FOCUS with Guarana extra is an enlivening brew of earthy black tea with tangy orange peel notes. 100% recyclable.",
    "product_category":"Beverage",
    "product_price": 3.50,
    "product_quantity":"100",
    "product_image": "https://www.nestle.com.my/sites/g/files/pydnoa251/files/lively-tea-focus-thumb.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Lipton Ice Lemon Tea 1.5L",
    "product_description":" Enjoy the unlimited refreshment with Lipton Ice Lemon Tea. Its classic iced black tea is infused with the burst of zesty lemon, for an exceptional iced tea taste. Tasty and refreshing.",
    "product_category":"Beverage",
    "product_price": 4.80,
    "product_quantity":"100",
    "product_image": "https://www.aceminimart.sg/wp-content/uploads/LIPTON-ICE-LEMON-TEA-450ML.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Lupak Butter In Foil Salted 200G",
    "product_description":"Lurpak Salted Butter has a fresh, pure buttery taste that is great for cooking and baking. It is also great as spreads since the saltiness does not overpower the true buttery taste of the butter.",
    "product_category":"Dairy",
    "product_price": 15.25,
    "product_quantity":"100",
    "product_image": "https://www.alaincoop.com/medias/?context=bWFzdGVyfGltYWdlc3wyNzYxM3xpbWFnZS9qcGVnfGg5Yi9oNzIvODc5NjUyNTAwMjc4MnxlNzY4OWMxODkwMGZjYjM0YzdiM2JlOWEwYWExMzQyMzJjMjhkZDQzOWYwNWU2OWQ0Y2IxOTgxMWFkYzc2MmE5"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Tatura Bega Salted Butter 250G",
    "product_description":"Tatura Salted Butter is a great all-purpose butter and also the perfect companion in the kitchen. It tastes so great on its own, spread on a warm piece of bread. You can always trust its flavour to elevate the taste of all your favourite dishes.",
    "product_category":"Dairy",
    "product_price": 16.40,
    "product_quantity":"100",
    "product_image": "https://shoplineimg.com/5f43709637bed500306a4248/6048bd4306dbb00011fa487e/800x.webp?source_format=png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"TRU Blue Garlic Butter 150G",
    "product_description":"Tru Blue Garlic Butter Spread is made with real garlic. It is a tasty garlicy butter spread that can be used on bread or crackers or used in preparing your favourite dishes.Made with real garlicUsed on breads or in preparing your fav.",
    "product_category":"Dairy",
    "product_price": 10.30,
    "product_quantity":"100",
    "product_image": "https://cdn0.woolworths.media/content/wowproductimages/large/071247_5.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Buttercup Dairy Spread 500G",
    "product_description":"Palm Oil,Palm Kernel Oil,Milk Fat,Milk Powder,Salt,Soya Lecithin,Contains Permitted Emulsifier, Flavourings (contains Milk) and Colouring (Beta Carotene).",
    "product_category":"Dairy",
    "product_price": 12.85,
    "product_quantity":"100",
    "product_image": "https://cdn-dbbdp.nitrocdn.com/GDkOcynMYgxaEeTWojJnoXqhBsjxtXiS/assets/static/optimized/rev-ee5d418/image/cache/catalog/Products/BAKING/buttercup%20250g-550x550.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Marigold HL Milk 1L",
    "product_description":"Milk Solids,Calcium,Vitamin C,Vitamin E,Vitamin B3,Vitamin B6,Vitamin B1,Vitamin B12,Vitamin A,Vitamin D3,Folic Acid,Contains Permitted Food Conditioner (Emulsifier, Stabiliser and Enzyme) and Flavouring.",
    "product_category":"Dairy",
    "product_price": 7.69,
    "product_quantity":"100",
    "product_image": "https://www.aplusgrocer.com.my/3338-large_default/marigold-hl-milk-plain-1l.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Marigold HL Strawberry Milk 1L",
    "product_description":"Solids,Sucrose,Strawberry Juice Concentrate,Calcium,Vitamin C,Vitamin E,Vitamin B3,Vitamin B6,Vitamin B1,Vitamin A,Vitamin B12,Vitamin D3,Folic Acid,Contains Permitted Food Conditioner (Emulsifier and Stabiliser), Flavouring and Colouring.",
    "product_category":"Dairy",
    "product_price": 7.69,
    "product_quantity":"100",
    "product_image": "https://www.desasegar.com.my/storage/media/filemanager/dairy/Marigold%20HL%20Milk%20Strawberry%201L.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Marigold HL Chocolate 1L",
    "product_description":"Milk Solids,Sucrose,Cocoa Powder,Calcium,Vitamin C,Vitamin E,Vitamin B3,Vitamin B6,Vitamin B1,Vitamin A,Vitamin B12,Vitamin D3,Folic Acid,Contains Permitted Food Conditioner (Emulsifier and Stabiliser) and Flavouring.",
    "product_category":"Dairy",
    "product_price": 7.69,
    "product_quantity":"100",
    "product_image": "https://www.desasegar.com.my/storage/media/filemanager/dairy/Marigold%20HL%20Milk%20Chocolate%201L.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Lactel FF Blueberry Yogurt 125G",
    "product_description":"Milk Solids,Mixed Fruits 6% (Apple, Nata de Coco, Blueberry - contains Citric Acid, Sorbic Acid),Sugar,Stabiliser,Dicalcium Phosphate,Mixed Live Culture (Streptococcus Thermophilus, Lactobacillus Bulgaricus),Flavourings,Contains Stabiliser as Permitted Food Conditioner,Contains Permitted Flavouring,All Additives are of Plant or Synthetic Origin.",
    "product_category":"Dairy",
    "product_price": 2.55,
    "product_quantity":"100",
    "product_image": "https://d11vuao38tfjvv.cloudfront.net/files/dbda94df7acc3ba52f51e6405fbaf3939803d50337fa80a71450cec45df800ef.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Lactel FF Strawberry Yogurt 125G",
    "product_description":"Milk Solids,Strawberry Fruit 5% (contains Citric Acid, Sorbic Acid),Sugar,Stabiliser,Dicalcium Phosphate,Mixed Live Culture (Streptococcus Thermophilus, Lactobacillus Bulgaricus),Flavourings,Colouring,Contains Stabiliser as Permitted Food Conditioner,Contains Permitted Flavouring and Colouring (Anthocyanin),All Additives are of Plant or Synthetic Origin.",
    "product_category":"Dairy",
    "product_price": 2.55,
    "product_quantity":"100",
    "product_image": "https://d11vuao38tfjvv.cloudfront.net/files/fa2f34199455542ba4880637e42db07a8169ca257a39f220741158410c6d9abc.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Emborg Parmesan Shredded Cheese 150G",
    "product_description":"Pasteurized Cow's Milk,Salt,Vegetarian Rennet,Preservative E1105 (Lysozyme From Egg Protein),Potato Starch.",
    "product_category":"Dairy",
    "product_price": 14.59,
    "product_quantity":"100",   
    "product_image": "https://mygroser.s3.ap-southeast-1.amazonaws.com/productImages/1000X1000/1634541403456-parmesan%20cheese.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"SCS Original Cheese Slices 200G",
    "product_description":"Cheese (Pasteurised Milk, Salt, Culture, Enzyme (Rennet)),Water,Butter (Cream, Water, Salt),Milk Solids,Emulsifiers (E331, E339),Salt,Preservative (E200),Acidity Regulator (E330),Lecithin (from Soy).",
    "product_category":"Dairy",
    "product_price": 11.15,
    "product_quantity":"100",   
    "product_image": "https://www.luluhypermarket.com/medias/383458-001.jpg-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wyMjA3MTd8aW1hZ2UvanBlZ3xoZDgvaGM1LzEwNTY3NDg0NTA2MTQyLzM4MzQ1OC0wMDEuanBnXzEyMDBXeDEyMDBIfDdiZDdiZDgxYzljZTBiMGYyMzI3ZmQ1MjYxYmUxNGNkZjA2OTk2MDRlNTAxNDViNWI2M2RmOGIxZTUzYjFhYTc"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Chesdale Cheese Plain 12S 250G",
    "product_description":"Chesdale Plain Cheese 500g.",
    "product_category":"Dairy",
    "product_price": 10.35,
    "product_quantity":"100",   
    "product_image": "https://cdn-everrise-estore.azureedge.net/cache/product/0100008301_11042022112956-1000x1024h.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Yeos Curry Chicken Can 405G",
    "product_description":"Yeo's Chicken Curry with Potatoes are made with selected ingredients, with full of flavor and aroma. It is ready-to-eat and best served with hot rice, bread or chapatti. Contains no preservatives, no added MSG and absolutely halal.",
    "product_category":"Canned Food",
    "product_price": 9.10,
    "product_quantity":"100",   
    "product_image": "https://www.desasegar.com.my/storage/media/filemanager/canned%20food/Yeos%20Curry%20Chicken%20405g.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Hosen Mandarin Orange 312G",
    "product_description":"Hosen Quality brand is a winner of 'Singapore Promising Brand Award' 2 years in a row, which is a true recognition of our quality and commitment. Freshly picked and packed is their commitment to pluck fruits and vegetables at the freshest peak and pack the freshest from every harvest.",
    "product_category":"Canned Food",
    "product_price": 3.65,
    "product_quantity":"100",   
    "product_image": "https://eborong.com.my/wp-content/uploads/2019/03/hosen_mandarin_312_01.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Ayam Brand Baked Bean 425G",
    "product_description":"Big and tender imported Great Northern Beans. Same great taste tomato sauce recipe with 48% reduced sugar.",
    "product_category":"Canned Food",
    "product_price": 4.15,
    "product_quantity":"100",   
    "product_image": "https://lzd-img-global.slatic.net/g/p/398f33abaaf11dfd6a51afcdb65c3052.jpg_720x720q80.jpg_.webp"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Ayam Brand Mackerel In Tomato Sauce 425G",
    "product_description":"Ayam Brand™ selects only cold oceans' mackerels. The fishes are tasty, fatty, tender and full of natural Omega 3. Mackerel is especially rich in Vitamin B12 which is ideal for our nervous system and cannot be found in fruits and vegetables. Contain NO preservatives and no added MSG.",
    "product_category":"Canned Food",
    "product_price": 9.25,
    "product_quantity":"100",   
    "product_image": "https://cf.shopee.com.my/file/2109ae1c25fb7359087250e592ad8c25"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Kimball Chick Peas 400G",
    "product_description":"Garbanzo Beans,Water,Salt,Sugar,Contains Stabilizers as Permitted Food Conditioners.",
    "product_category":"Canned Food",
    "product_price": 4.79,
    "product_quantity":"100",   
    "product_image": "https://d11vuao38tfjvv.cloudfront.net/files/3a89f0008b26d436ec32cf5d340f5bfcce57c86507f49718e240e8bc0c21964a.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Ferrero Rocher Premium Chocolate (24 pcs)",
    "product_description":"Ferrero Rocher is a chocolate sweet made by Italian chocolatier Ferrero SpA. The chocolates consist of a whole roasted hazelnut encased in a thin wafer shell filled with hazelnut cream including vegetable oil and covered in milk chocolate and chopped hazelnuts.",
    "product_category":"Confectionary",
    "product_price": 50.00,
    "product_quantity":"100",   
    "product_image": "https://www.bigbasket.com/media/uploads/p/l/119834_9-ferrero-rocher-chocolate.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Skittles Fruit Flavour Candies Original 45g",
    "product_description":"Skittles candy products, produced by the Wm. Wrigley Jr. Company, come in a wide variety. Most of the varieties are available only in particular regions of the world. Flavours:Grape (purple)Lemon (yellow)Green Apple (green).Orange (orange) Strawberry (red).",
    "product_category":"Confectionary",
    "product_price": 2.20,
    "product_quantity":"100",   
    "product_image": "https://mygroser.s3.ap-southeast-1.amazonaws.com/productImages/1000X1000/1598410354819-1597303660132-skittleori.jpeg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Jelly Belly Bean Boozled Jelly Beans Spinner Set 100g",
    "product_description":"Are you brave enough? Jelly Belly Bean Boozled jelly beans are a collection of 20 flavors and included with a spinner game- fun for the children and family.",
    "product_category":"Confectionary",
    "product_price": 48.90,
    "product_quantity":"100",   
    "product_image": "https://m.media-amazon.com/images/I/61plqIoUPmL._AC_SL1146_.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Nougat Original Crunchy 100g",
    "product_description":"Golden Boronia Original Crunchy Nougat is made with the natural goodness of honey, almond and golden corn with absolutely no artificial colouring.",
    "product_category":"Confectionary",
    "product_price": 17.00,
    "product_quantity":"100",   
    "product_image": "https://golden-boronia.com/wp-content/uploads/2018/08/GB_100g_07.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Cadbury Dairy Milk Chocolate",
    "product_description":"Cadbury Dairy Milk Chocolate is Made from Fresh Milk & Cocoa Beans. Cadbury goodness begins with a bite of creamy milk & cocoa mix, and it will bring a whole new world of endless inherent goodness of chocolate.",
    "product_category":"Confectionary",
    "product_price": 8.20,
    "product_quantity":"100",   
    "product_image": "https://www.cadbury.co.za/sites/default/files/2021-04/CDM_Milk%20ChocCarousel_0.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Godiva 8 Mini Chocolate Bar 90g Roasted Almond Dark",
    "product_description":"When it comes to chocolate bars, you can't go wrong with GODIVA's delicious options. With the variety of different options, there's a great choice for any recipient. Or if you want to surprise them with a delicious assortment.",
    "product_category":"Confectionary",
    "product_price": 17.90,
    "product_quantity":"100",   
    "product_image": "https://cf.shopee.com.my/file/af3efe9f14860a45bed7159b2b0ea9c6"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"OLDTOWN White Coffee 3-in-1 Hazelnut White Coffee",
    "product_description":"A rich fragrant Hazelnut flavoured white coffee blend. Creamy, nutty and unique, it leaves a tantalising mouth feel.",
    "product_category":"Tea, Coffee, Chocolate Drinks",
    "product_price": 15.00,
    "product_quantity":"100",   
    "product_image": "https://cf.shopee.com.my/file/7c8272a40b14f1f11bf936acb52071b9"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Super Essenso Microground Colombian Blend Instant Black Coffee 20 Sticks x 2g (40g)",
    "product_description":"From Colombia, birthplace of some of the world's most elite brews, comes a pure-Arabica creation: Essenso™ MicroGround Black Coffee. An iconic union of instant coffee powder and finely ground single-origin Colombian coffee beans, it owes its exquisite taste to MicroPlus™, a proprietary technique we use to preserve the very essence of prized beans. Finally, a platinum standard borne out of finely ground coffee and premium instant coffee.Essence of the coffee beans is captured as fine coffee grinds in your cup.",
    "product_category":"Tea, Coffee, Chocolate Drinks",
    "product_price": 19.60,
    "product_quantity":"100",   
    "product_image": "https://cf.shopee.com.my/file/2d0edee3885d28588d906a04a3ceae14"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name":"Daesang OFood Gochujang Sauce 300g",
    "product_description":"A quintessential flavour for Korean dishes. This Korean chilli miso paste, known as gochujang, is made with sundried chillis to give a rich, fiery flavour. Produced in the town of Sunchang, famous for its delicious chilli paste this gochujang chilli paste, this paste is great for adding heat and flavour to any Korean dish. Perfect for bibimbap or stewed traditional dishes. ",
    "product_category":"Sauce & Dressing",
    "product_price": 11.50,
    "product_quantity":"100",   
    "product_image": "https://cdn.shopify.com/s/files/1/0429/3761/4503/products/131479-1-1_500x.jpg?v=1664961664"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Masterfoods Thyme Leaves 10g",
    "product_description":"MasterFoods™ Thyme Leaves are an aromatic, floral herb with woody notes. Thyme Leaves have a dry aroma and slightly minty flavour. This herb is delicious in stews and casseroles. Used to flavour patés and terrines, thick vegetable soups, tomato and wine based sauces and in marinades for pork or game meats.",
    "product_category":"Condiments",
    "product_price": 9.90,
    "product_quantity":"100",   
    "product_image": "https://www.masterfoods.com.au/-/media/masterfoodsau/productimages/heroimages/hero93716130.jpg?h=515&la=en-AU&w=515&hash=51F48250311320F32DCA41CAF13451A8DAE9793B"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Hexa Basil Leaves 20g",
    "product_description":"Basil leaves are used in a variety of culinary preparations. It is known for being the main ingredient in traditional pesto and is also a favorite seasoning in tomato-based pasta sauces. In addition to the flavour, the culinary herb is said to preserve and enhance the properties of the food. Next, It adds a depth and flavor that is not rivaled by other herbs.",
    "product_category":"Condiments",
    "product_price": 4.25,
    "product_quantity":"100",   
    "product_image": "https://www.desasegar.com.my/storage/media/filemanager/herb%20n%20spices/hexa%20basil.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Kewpie Japanese Style Mayonnaise 310ml",
    "product_description":"Japan’s most beloved mayonnaise since 1925. KEWPIE MAYONNAISE JAPANESE STYLE is made purely from egg yolks. It is also 100% Halal and comes in a convenient squeeze-bottle.",
    "product_category":"Sauce & Dressing",
    "product_price": 10.50,
    "product_quantity":"100",   
    "product_image": "https://qsrtrading.com.my/wp-content/uploads/2020/05/Kewpie-Mayonnaise-Japanese-Style-310ml.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Kewpie Hot Spicy Dressing 210ml",
    "product_description":"Our rich KEWPIE HOT SPICY DRESSING blends the hot, spicy, sweet and sour flavours together, giving your salad a fiery taste. It also goes great with pan frying, roasting and even as meat or fish marinade. No added MSG.",
    "product_category":"Sauce & Dressing",
    "product_price": 8.30,
    "product_quantity":"100",   
    "product_image": "https://qsrtrading.com.my/wp-content/uploads/2020/05/Kewpie-Dressing-Hot-Spicy-210ml.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "MAGGI Tomato Ketchup 475g",
    "product_description":"MAGGI Tomato Ketchup - Bursting With Flavours Just add a dash of this sauce into your dishes for a rich, savoury, tomato flavour. Fresh juicy tomatoes, brimming with flavour. Experience the perfect balance of sweet and sour flavours in your cooking.",
    "product_category":"Sauce & Dressing",
    "product_price": 4.00,
    "product_quantity":"100",   
    "product_image": "https://cdn.shopify.com/s/files/1/0095/1651/5390/products/002373-1-1_600x.jpg?v=1657641859"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Mahsuri Spicy Sweet & Sour Sauce 530g",
    "product_description":"Made from a non-genetically modified soy, Mahsuri offers a balance of sweetness and flavours. This can be used in recipes or as a dipping sauce on its own. A product of Malaysia.",
    "product_category":"Sauce & Dressing",
    "product_price": 5.45,
    "product_quantity":"100",   
    "product_image": "https://mahsurifood.com.my/wp-content/uploads/2020/11/kip-5.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Kipas Udang Sweet Soya Bean Sauce 645ml",
    "product_description":"Habhal's sweet soya bean sauce contains vitamin A. One of our favourites here at food sanctuary, Habhal sweet soy bean sauce is versatile and delicious. Use this thick, rich caramel-coloured sauce to add an aromatic and it is a wonderful marinade on chicken, meat, vegetables, this sauce works well alone or mixed with other flavours.",
    "product_category":"Sauce & Dressing",
    "product_price": 8.70,
    "product_quantity":"100",   
    "product_image": "https://www.lollipop.com.my/image/cache/catalog/product_image/canned/Cap-Kipas-Udang-Soya-Bean-Sauce-Sweet-645ml-515x515.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "MAGGI Cukup Rasa 100g",
    "product_description":"A sprinkle of MAGGI® CukupRasa™ transforms your family favourites from good to great. It’s got fresh onions and garlic, the perfect balance of spices and delicious meaty taste! No need to add salt when you use MAGGI® CukupRasa™. It is suitable for all kinds of cooking methods like stir-fry, steam, frying and marination.",
    "product_category":"Condiments",
    "product_price": 3.10,
    "product_quantity":"100",   
    "product_image": "https://senglee.my/wp-content/uploads/sites/11/2021/07/2-7.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Ajinomoto MSG 300g",
    "product_description":"AJI-NO-MOTO® Umami seasoning (flavour enhancer) is a world renowned brand for Monosodium Glutamate (MSG). AJI-NO-MOTO® provides Umami taste (savory/meaty taste) and is widely used not only by household to enhance the taste of any dishes but also by hawkers and professional chefs in restaurants all over the world.",
    "product_category":"Condiments",
    "product_price": 5.70,
    "product_quantity":"100",   
    "product_image": "https://cdn.shopify.com/s/files/1/0559/2032/8895/products/AjinomotoMSG300g_1024x1024@2x.jpg?v=1632984178"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "BABA's Tumeric Powder 125g",
    "product_description":"BABA'S turmeric powder is made from clean, pure and finest quality turmeric, processed by using modern techniques and packed according to strict hygienic standards. This powder is high in essential oils and purity levels, with golden yellow vibrant colour. It's free from MSG, additives or preservatives and simply the best choice!",
    "product_category":"Condiments",
    "product_price": 2.60,
    "product_quantity":"100",   
    "product_image": "https://www.babas.com.my/images/product/pure-spice-2.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Mackays Three Fruit Marmalade 340g",
    "product_description":"Using traditional open copper pans, the highest quality Spanish citrus fruits and our authentic methods, we ensure rich fruit flavours in every batch and that special home-made taste you expect from Mackays.",
    "product_category":"Jam",
    "product_price": 12.10,
    "product_quantity":"100",   
    "product_image": "https://www.mackays.com/uploads/images/products/large/MC933_Three_Fruit_Marmalade_.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Chivers Mixed Fruit Jam 340g",
    "product_description":"Chivers Mixed Fruits Jam is a fantastic combination of sweetness and berry intensity for a real taste bud pleaser. Spread it on all kinds of bread, pancakes or even waffles for an energy packed start your day!",
    "product_category":"Jam",
    "product_price": 9.60,
    "product_quantity":"100",   
    "product_image": "https://pasaralafbaru.com/wp-content/uploads/2021/05/IMG_20210325_143626-scaled.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Lady's Choice Strawberry Jam 400g",
    "product_description":"Totally a perfect choice for a quick bite with LADY'S CHOICE JAM STRAWBERRY. A spread in tasty flavour with smooth texture to offer easy spreading and ready to be eat right away. Best companion for those who always prefer a quick breakfast.",
    "product_category":"Jam",
    "product_price": 8.80,
    "product_quantity":"100",   
    "product_image": "https://www.eazymart.com/storage/products/eazy0455.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "St. Dalfour Strawberry High Fruit Content Spread 284g",
    "product_description":"100% fruit, Traditional French recipe, All natural ingredients, No preservatives, No artificial flavours or colours.",
    "product_category":"Jam",
    "product_price": 14.50,
    "product_quantity":"100",   
    "product_image": "https://lzd-img-global.slatic.net/g/p/a17b21527b8aa10d05b64895c52ee1f2.jpg_720x720q80.jpg_.webp"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Emborg Cream Cheese 200g",
    "product_description":"Emborg Cream Cheese is made from real European cream. It is a fresh cheese, soft and creamy with a mild and smooth flavour. Enjoy the European Cream Cheese fresh with its delicious and intense creamy flavour by adding it to bread, bagels and crackers, or use it in quinces and gratins for a delicious creamy flavour.",
    "product_category":"Dairy",
    "product_price": 11.90,
    "product_quantity":"100",   
    "product_image": "https://cdn.shopify.com/s/files/1/0293/2667/1965/products/EMB.jpg?v=1659512161"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "McCormick Mixed Herbs 10g",
    "product_description":"McCormick Mixed Herbs combines a classic herbal blend of marjoram, basil, oregano and thyme. Its versatility makes it a kitchen essential to be used generously.",
    "product_category":"Condiments",
    "product_price": 9.90,
    "product_quantity":"100",   
    "product_image": "https://bigboxasia.com/media/catalog/product/cache/a59b1e08797b716e5a7d05eb509aa710/u/n/untitled_design_-_2022-06-29t105420.220.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Prai Gula Course Sugar 1KG",
    "product_description":"For half a century, Gula Prai has been the premium sugar brand in Malaysia and the most popular choice among consumers.",
    "product_category":"Condiments",
    "product_price": 3.00,
    "product_quantity":"100",   
    "product_image": "https://baloy.com.my/content/images/thumbs/5e5a9aa468805f31c20276ca_prai-sugar-gula-pasir-kasar-1kg.jpeg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Yeo's White Vinegar 330ml",
    "product_description":"Yeo's Vinegar is suitable for a wide range of cooking purposes: Pickles, Sauces, Culinary dishes.",
    "product_category":"Sauce & Dressing",
    "product_price": 2.50,
    "product_quantity":"100",   
    "product_image": "https://yeos.com.my/wp-content/uploads/2019/03/vinegar-big.jpg.webp"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "LEE KUM KEE White Vinegar 473ml",
    "product_description":"Crystal clear and refreshing, Lee Kum Kee White Vinegar is perfect for pickling, making salads, sweet and sour dishes and sushi. Simply add a few drops to enhance the aroma and flavour of your favourite dishes.",
    "product_category":"Sauce & Dressing",
    "product_price": 8.00,
    "product_quantity":"100",   
    "product_image": "https://d1e1vgxjd1htwd.cloudfront.net/-/media/my-site---homecook/white-vinegar_473ml_my.png?h=1000&w=465&hash=5A1CEF2359BF9BA326DC76BDA49E3FD65395B50B"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Anchor Aerosol Dairy Cream",
    "product_description":"Anchor Aerosol Dairy Cream delivers ready to use whipped cream in an easy-to-use aerosol canister. With a long shelf life, you can enjoy consistent and convenient whipped cream ready for when you need it. Perfect as a dairy topping for beverages and desserts.",
    "product_category":"Dairy",
    "product_price": 18.00,
    "product_quantity":"100",   
    "product_image": "https://cdn.store-assets.com/s/338100/i/24619972.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Emborg Whipping Cream 200ml",
    "product_description":"Take your sweet recipes to the next level with a sweet and smooth cream from Emborg. We have created delicious sweetened creams for you to enjoy with your favourite dessert",
    "product_category":"Dairy",
    "product_price": 11.50,
    "product_quantity":"100",   
    "product_image": "https://www.desasegar.com.my/storage/media/filemanager/baking/emborg%20whipping%20cream.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "THE PINK TEA BOX: Love Heart Tea",
    "product_description":"Our pretty Love Heart tea, is the perfect gift for any tea lover.  Best loose leaf tea / best tasting Australian tea.  Contains: Green tea, sugar hearts (sugar, ALMONDS, invert sugar, glucose syrup, colouring food extracts: beetroot juice concentrate, concentrated lemon juice), rose petal, rosebuds, natural flavour.",
    "product_category":"Tea, Coffee & Chocolate Drinks",
    "product_price": 61.90,
    "product_quantity":"100",   
    "product_image": "https://cdn.shopify.com/s/files/1/0488/2461/5079/products/ThePinkTeaBoxLoveHeartLooseLeafTea_590x.jpg?v=1618780890"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Sunglo Natural Sour Cream 210g",
    "product_description":"Great for baking, dips, salads and nachos.",
    "product_category":"Dairy",
    "product_price": 7.00,
    "product_quantity":"100",   
    "product_image": "https://lzd-img-global.slatic.net/g/p/da399b385b1356c1aedd09587d73961e.jpg_720x720q80.jpg_.webp"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Gardenia Bonanza White Sandwich Bread 20 Slices 500g",
    "product_description":"High in vitamin B1, B2, B3, calcium and iron. No cholesterol, artificial flavouring or colouring. Bromate free. Freshness guaranteed: Estimated product life for 3 days including delivery day.",
    "product_category":"Bread & Pastry",
    "product_price": 4.50,
    "product_quantity":"100",   
    "product_image": "https://www.thebig3grocery.com.my/image/cache/catalog/Bread%20/heromarket_2010007501_2010007501-1-500x500.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Farm Fresh Full Cream Milk 2L",
    "product_description":"Made with 100% pure fresh milk, packed in a 2 liters bottle. A good source of nutrition, fresh milk is great with cereals and as is.",
    "product_category":"Dairy",
    "product_price": 16.90,
    "product_quantity":"100",   
    "product_image": "https://mygroser.s3.ap-southeast-1.amazonaws.com/productImages/1000X1000/1581045845543-FF%20fresh%202L.jpeg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "MARIGOLD Mixed Berries Yogurt Fat Free 130g",
    "product_description":"Direct from the green pastures of Australia, contains all the natural goodness of fresh Australian cow's milk.Marigold dairy contains all the natural goodness of fresh Australian cow's milk. Smooth, creamy and fresh that is both delicious on its own and tastes great with coffee too.",
    "product_category":"Dairy",
    "product_price": 3.28,
    "product_quantity":"100",   
    "product_image": "https://www.aplusgrocer.com.my/4743-large_default/marigold-0-fat-yogurt-mixed-berries-135ml.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Feldbacher Zwieback Klassik Rusks",
    "product_description":"The delicate, mild taste of Feldbacher rusk. Yummy rusks made in Germany yet super popular in Austria!",
    "product_category":"Bread & Pastry",
    "product_price": 3.25,
    "product_quantity":"100",   
    "product_image": "https://austrianfood.co.uk/images/thumbs/0000384_feldbacher-zwieback-klassik-rusks-best-before-0722_510.jpeg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "SmartHeart Cat Food 1.2kg Mackerel",
    "product_description":"Corn,Poultry Meal,Fish Meal,Corn Gluten Meal,Soybean Meal,Chicken Fat,Brewers Dried Yeast,Lecithin,Fish Oil,Vitamins and Minerals,Taurine,Antioxidants,Flavoring,Food Coloring.",
    "product_category":"Pet food",
    "product_price": 14.99,
    "product_quantity":"100",   
    "product_image": "https://www.petswonderland.com/media/catalog/product/cache/4601bc3edc3d99d2758a5e315967177b/0/1/019349_smartheart_cat_mackerel_1.2kg.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Probalance Chicken With Veggie 400G",
    "product_description":"Selected Meat and Meat by-Products (Derived from Chicken, Beef and Lamb),Cereal,Vegetable Protein,Gels,Salt,Sodium Nitrite,Oligosaccharide,Glucosamine,Chondroitin,Water.",
    "product_category":"Pet food",
    "product_price": 5.20,
    "product_quantity":"100",   
    "product_image": "http://www.probalance.com.my/wp-content/uploads/2019/11/chicken-in-veggie-400g-edited2.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Whiskas Tuna 1.2kg",
    "product_description":"Wholegrain Cereal (Corn, Wheat),Poultry and Poultry by Products,Soy Bean Product (Full Fat Soy Bean, Soy Bean Meal),Corn Gluten Meal,Vegetables Oil (Palm Sterine, Soy Oil),Ocean Fish,Wheat Flour,Minerals,Iodised Salt,Vitamins,Taurine,Methionine,Food Coloring,Preservatives,Flavour.",
    "product_category":"Pet food",
    "product_price": 14.30,
    "product_quantity":"100",   
    "product_image": "https://s3-eu-west-1.amazonaws.com/w3.cdn.gpd/me.whiskas.14/large_whiskas-tuna-flavour-636564627251243653.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Pedigree Beef 1.15kg",
    "product_description":"Meat and Meat by products (Chicken, Beef, Sheep),Gelling Agents,Fibre,Wheat Gluten,Minerals,Sunflower Oil,Colours,Vitamins,Flavour,Preservative.",
    "product_category":"Pet food",
    "product_price": 14.30,
    "product_quantity":"100",   
    "product_image": "https://cdn.shopify.com/s/files/1/0428/6129/7830/products/012355-1-1_9b6debc1-7430-4266-bd2a-e4981e47ed70_500x.jpg?v=1635460533"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Kelloggs Corn Flakes Jumbo 500G",
    "product_description":"Every Bite of these crispy ,golden flakes is just as delicious as the first.You'll be on your way to a great day when you pour a bowl of Kellogg's Corn Flakes cereal into your breakfast.",
    "product_category":"Cereals",
    "product_price": 12.90,
    "product_quantity":"100",   
    "product_image": "https://cf.shopee.com.my/file/acba2945acc59a5f1bcc1cc5b32c42e5"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Nestum All Family Cereal Original 500G",
    "product_description":"Wholemeal Wheat,Rice,Malt Extract (contains Barley),Sugar,Corn Grits,Minerals,Salt,Vitamins,Maltodextrin,Contains Stabiliser as Permitted Food Conditioner,Contains Permitted Flavouring (Vanillin),All Additives are of Synthetic Origin.",
    "product_category":"Cereals",
    "product_price": 7.80,
    "product_quantity":"100",   
    "product_image": "https://d11vuao38tfjvv.cloudfront.net/files/0d77cefd7660feaa1403f3d2108e5a355fe11ce87b8b612944852fda4263fa92.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Nestle KoKo Krunch 330G",
    "product_description":"Breakfast cereal with great, chocolate-y taste to kickstart your kids' school day. • With carbohydrates and fibre to provide your kids energy.",
    "product_category":"Cereals",
    "product_price": 10.60,
    "product_quantity":"100",   
    "product_image": "https://www.desasegar.com.my/storage/media/filemanager/breakfast/Nestle%20Koko%20Krunch%20330g.png"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Nestle Fitness Cereal 330G",
    "product_description":"If you are what you eat, you might want to get munching now! Eat your way to a healthier, stronger body with FITNESSE Cereal for a bowl of complete and healthy breakfast. With whole grain as its main ingredients, this simply delicious and naturally gorgeous cereal has 10 vitamins and minerals, including calcium and iron.",
    "product_category":"Cereals",
    "product_price": 15.20,
    "product_quantity":"100",   
    "product_image": "https://www.nestle-cereals.com/global/sites/g/files/qirczx806/files/styles/1_1_768px_width/public/2022-07/Fitness.png?itok=tEcMPdsC"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "MAMEE Monster Black Paper 8X25G",
    "product_description":"Wheat Flour (Contains Gluten), Vegetable Oil [Palm Oil, Antioxidant (Butylated Hydroxytoluene)], Salt, Flavour Enhancers (Monosodium Glutamate, Disodium5'-ribonucleotides), Flavouring Substance, Black Pepper, Spices, Stabilisers (Triphosphates, Potassium Carbonates, Guar Gum), Soy Sauce (Contains Soybean).",
    "product_category":"Snacks",
    "product_price": 3.20,
    "product_quantity":"100",   
    "product_image": "https://mamee.com/wp-content/uploads/2022/03/mamee3.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Mister Potato BBQ 70G",
    "product_description":"Only the freshest potatoes imported from farms around the world are used. Bite into the yummiest chips and crisps this side of the world!",
    "product_category":"Snacks",
    "product_price": 2.60,
    "product_quantity":"100",   
    "product_image": "https://gogopasar.com/images/media/2022/06/wYM6Y01511.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Twist Chipster Original 60G",
    "product_description":"Potatoes,Non-Hydrogenated Vegetable Oil (Palm),Tapioca Starch,Salt,Sugar,Flavour Enhancers (Monosodium Glutamate (E621), Disodium 5'-Guanylate (E627) and Disodium 5'-Inosinate (E631)),Flavours,Acidity Regulator (Sodium Acetate (E262) and Sodium Diacetate (E262(ii)) and Anticaking Agent (Silicon Dioxide (E551)),Contains Permitted Flavour Enhancers, Flavours and Food Conditioners,Food Additives are Sourced from Plant and Synthetic Origin.",
    "product_category":"Snacks",
    "product_price": 3.00,
    "product_quantity":"100",   
    "product_image": "https://angelland.my/wp-content/uploads/2020/10/TWIST-CHIPSTER-ORIGINAL-60g.jpg"
}

###

POST http://localhost:5004/quatro_product/create
Content-Type: application/json

{
    "product_name": "Jacker Wavy Chips 60G Spicy Nacho",
    "product_description":"Potatoes,Vegetable Oil,Spicy Nacho Seasoning,Salt,Sugar,Permitted Flavour Enhancer (621) MSG.",
    "product_category":"Snacks",
    "product_price": 2.15,
    "product_quantity":"100",   
    "product_image": "https://www.ofih.com.my/wp-content/uploads/2020/02/Jacker-Wavy-Chips-60g-Spicy-Nacho.png"
}

