###
POST http://localhost:5004/quatro_transaction/create
Content-Type: application/json

{
      "transaction_id": "3",
      "product_id": "10",
      "user_id": "5",
      "product_name": "Gardenia Waffles- Chocolate",
      "product_quantity": "2",
      "product_price": "1.50",
      "transaction_timestamp": "" 
}


###
POST http://localhost:5004/quatro_transaction/update
Content-Type: application/json

{
 "user_id" : "5"
}

###
POST http://localhost:5004/quatro_transaction/update_discount
Content-Type: application/json

{
 "user_id" : "2"
}

###
POST http://localhost:5004/quatro_transaction/update_payment
Content-Type: application/json

{
 "user_id" : "2"
}

###
GET http://localhost:5004/quatro_transaction/get_details
Content-Type: application/json

{
    "user_id": "5"
}